import type { ICustomer, IItem } from "@/types"

export const dummyCustomers: ICustomer[] = [
  {
    id: "cust-001",
    name: "Acme Corporation",
    contactNo: "9876543210",
    email: "contact@acmecorp.com",
    address: "123 Business Park, Mumbai, Maharashtra 400001",
    openingBalance: 5000,
    openingDate: new Date("2024-01-01"),
    gstinNo: "27AABCU9603R1ZM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cust-002",
    name: "Tech Solutions Pvt Ltd",
    contactNo: "9988776655",
    email: "info@techsolutions.in",
    address: "456 Tech Tower, Bangalore, Karnataka 560001",
    openingBalance: 0,
    openingDate: new Date("2024-02-15"),
    gstinNo: "29BBCDE1234F1Z5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cust-003",
    name: "Retail Mart",
    contactNo: "9123456789",
    email: "manager@retailmart.com",
    address: "789 Market Street, Delhi, 110001",
    openingBalance: 2500,
    openingDate: new Date("2024-03-01"),
    gstinNo: "07CDEFG5678H1Z3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const dummyItems: IItem[] = [
  {
    id: "item-001",
    itemCode: "LAP-001",
    name: "Premium Laptop",
    category: "Electronics",
    hsnCode: "8471",
    barcodeNo: "8901234567890",
    unit: "PCS",
    conversionRate: 1,
    alternateUnit: "",
    purchasePrice: 35000,
    salePrice: 45000,
    wholesalePrice: 42000,
    quantityPrice: 40000,
    mrp: 48000,
    discountType: "percentage",
    saleDiscount: 5,
    stock: 25,
    minStock: 5,
    maxStock: 50,
    itemLocation: "Rack A-12",
    gstRate: 18,
    taxRate: 18,
    cessRate: 0,
    inclusiveOfTax: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "item-002",
    itemCode: "MOUSE-01",
    name: "Wireless Mouse",
    category: "Electronics",
    hsnCode: "8471",
    barcodeNo: "8901234567891",
    unit: "PCS",
    conversionRate: 1,
    alternateUnit: "",
    purchasePrice: 250,
    salePrice: 499,
    wholesalePrice: 450,
    quantityPrice: 400,
    mrp: 599,
    discountType: "percentage",
    saleDiscount: 10,
    stock: 150,
    minStock: 20,
    maxStock: 200,
    itemLocation: "Rack B-05",
    gstRate: 18,
    taxRate: 18,
    cessRate: 0,
    inclusiveOfTax: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "item-003",
    itemCode: "KEY-PRO",
    name: "Mechanical Keyboard",
    category: "Electronics",
    hsnCode: "8471",
    barcodeNo: "8901234567892",
    unit: "PCS",
    conversionRate: 1,
    alternateUnit: "",
    purchasePrice: 1500,
    salePrice: 2499,
    wholesalePrice: 2200,
    quantityPrice: 2000,
    mrp: 2999,
    discountType: "flat",
    saleDiscount: 200,
    stock: 75,
    minStock: 10,
    maxStock: 100,
    itemLocation: "Rack B-08",
    gstRate: 18,
    taxRate: 18,
    cessRate: 0,
    inclusiveOfTax: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "item-004",
    itemCode: "RICE-01",
    name: "Basmati Rice",
    category: "Grocery",
    hsnCode: "1006",
    barcodeNo: "8901234567893",
    unit: "KG",
    conversionRate: 1,
    alternateUnit: "",
    purchasePrice: 80,
    salePrice: 120,
    wholesalePrice: 110,
    quantityPrice: 100,
    mrp: 130,
    discountType: "percentage",
    saleDiscount: 5,
    stock: 500,
    minStock: 100,
    maxStock: 1000,
    itemLocation: "Warehouse-A",
    gstRate: 5,
    taxRate: 5,
    cessRate: 0,
    inclusiveOfTax: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "item-005",
    itemCode: "OIL-SUN",
    name: "Sunflower Oil",
    category: "Grocery",
    hsnCode: "1512",
    barcodeNo: "8901234567894",
    unit: "LTR",
    conversionRate: 1,
    alternateUnit: "",
    purchasePrice: 120,
    salePrice: 180,
    wholesalePrice: 165,
    quantityPrice: 155,
    mrp: 200,
    discountType: "percentage",
    saleDiscount: 8,
    stock: 200,
    minStock: 50,
    maxStock: 500,
    itemLocation: "Warehouse-B",
    gstRate: 5,
    taxRate: 5,
    cessRate: 0,
    inclusiveOfTax: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
