/**
 * Portal E-Way Bills Viewer
 * View E-Way Bills generated by others through the portal
 */

"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Loader2, Search, RefreshCw, ExternalLink, Truck } from "lucide-react"
import { eWayBillService, EWayBillUtils, type PortalEWayBill } from "@/lib/e-waybill-service"
import { toast } from "sonner"
import { format } from "date-fns"

export function PortalEWayBillsViewer() {
  const [loading, setLoading] = useState(false)
  const [date, setDate] = useState(format(new Date(), "dd/MM/yyyy"))
  const [eWayBills, setEWayBills] = useState<PortalEWayBill[]>([])

  const handleSearch = async () => {
    try {
      setLoading(true)
      const bills = await eWayBillService.getGeneratedByOthers(date)
      setEWayBills(bills)
      
      if (bills.length === 0) {
        toast.info("No E-Way Bills found for the selected date")
      } else {
        toast.success(`Found ${bills.length} E-Way Bill(s)`)
      }
    } catch (error: any) {
      console.error("Failed to fetch portal E-Way Bills:", error)
      toast.error(error.message || "Failed to fetch E-Way Bills from portal")
    } finally {
      setLoading(false)
    }
  }

  const formatDate = (dateString: string) => {
    try {
      // Government API returns DD/MM/YYYY format
      const [day, month, year] = dateString.split("/")
      return new Date(parseInt(year), parseInt(month) - 1, parseInt(day)).toLocaleDateString()
    } catch {
      return dateString
    }
  }

  const getStatusBadge = (status: string) => {
    const statusLower = status.toLowerCase()
    if (statusLower.includes("active")) {
      return <Badge variant="default">Active</Badge>
    } else if (statusLower.includes("cancel")) {
      return <Badge variant="outline">Cancelled</Badge>
    } else if (statusLower.includes("expir")) {
      return <Badge variant="destructive">Expired</Badge>
    }
    return <Badge variant="secondary">{status}</Badge>
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <Truck className="w-5 h-5" />
              E-Way Bills from Portal
            </CardTitle>
            <CardDescription>
              View E-Way Bills generated by others for your GSTIN through the government portal
            </CardDescription>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Search Form */}
        <div className="flex gap-4 items-end">
          <div className="flex-1 space-y-2">
            <Label htmlFor="date">Select Date</Label>
            <Input
              id="date"
              type="text"
              placeholder="DD/MM/YYYY"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSearch()}
            />
            <p className="text-xs text-muted-foreground">Format: DD/MM/YYYY</p>
          </div>
          <Button onClick={handleSearch} disabled={loading}>
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Searching...
              </>
            ) : (
              <>
                <Search className="w-4 h-4 mr-2" />
                Search
              </>
            )}
          </Button>
        </div>

        {/* Results Table */}
        {eWayBills.length > 0 && (
          <div className="border rounded-lg overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>E-Way Bill No</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Doc No</TableHead>
                  <TableHead>From</TableHead>
                  <TableHead>To</TableHead>
                  <TableHead className="text-right">Value</TableHead>
                  <TableHead>Mode</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Valid Upto</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {eWayBills.map((bill) => (
                  <TableRow key={bill.ewbNo}>
                    <TableCell className="font-mono text-sm">
                      {EWayBillUtils.formatEWayBillNo(bill.ewbNo)}
                    </TableCell>
                    <TableCell className="text-sm">{formatDate(bill.ewbDate)}</TableCell>
                    <TableCell className="text-sm">{bill.docNo}</TableCell>
                    <TableCell>
                      <div className="text-sm">
                        <p className="font-medium">{bill.fromTrdNm}</p>
                        <p className="text-xs text-muted-foreground">{bill.fromGstin}</p>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="text-sm">
                        <p className="font-medium">{bill.toTrdNm}</p>
                        <p className="text-xs text-muted-foreground">{bill.toGstin}</p>
                      </div>
                    </TableCell>
                    <TableCell className="text-right font-medium">
                      ₹{bill.totalValue.toLocaleString("en-IN")}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="text-xs">
                        {EWayBillUtils.getTransportModeLabel(bill.transMode)}
                      </Badge>
                    </TableCell>
                    <TableCell>{getStatusBadge(bill.status)}</TableCell>
                    <TableCell className="text-sm">{formatDate(bill.validUpto)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}

        {/* Empty State */}
        {!loading && eWayBills.length === 0 && (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <Truck className="w-12 h-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold">No E-Way Bills Found</h3>
            <p className="text-muted-foreground mb-4">
              Search for E-Way Bills generated by others for your GSTIN
            </p>
          </div>
        )}

        {/* Info Box */}
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg text-sm space-y-2">
          <p className="font-medium text-blue-900">About Portal E-Way Bills:</p>
          <ul className="list-disc pl-5 text-blue-800 space-y-1">
            <li>View E-Way Bills generated by suppliers or transporters for your GSTIN</li>
            <li>Useful for tracking incoming shipments</li>
            <li>Can verify and accept/reject E-Way Bills if needed</li>
            <li>Search by date to find all bills for a specific day</li>
          </ul>
        </div>

        {/* Quick Actions */}
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setDate(format(new Date(), "dd/MM/yyyy"))}
          >
            Today
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              const yesterday = new Date()
              yesterday.setDate(yesterday.getDate() - 1)
              setDate(format(yesterday, "dd/MM/yyyy"))
            }}
          >
            Yesterday
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              const lastWeek = new Date()
              lastWeek.setDate(lastWeek.getDate() - 7)
              setDate(format(lastWeek, "dd/MM/yyyy"))
            }}
          >
            Last Week
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
