"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Truck, FileText, RefreshCw } from "lucide-react"
import { PortalEWayBillsViewer } from "@/components/invoices/portal-ewaybills-viewer"
import { EWayBillSync } from "@/components/invoices/ewaybill-sync"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { useState } from "react"

export default function EWayBillManagementPage() {
  const [refreshKey, setRefreshKey] = useState(0)

  const handleSyncComplete = () => {
    // Trigger refresh of portal viewer
    setRefreshKey(prev => prev + 1)
  }

  return (
    <div className="p-4 sm:p-6 space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight flex items-center gap-2">
            <Truck className="w-6 sm:w-8 h-6 sm:h-8" />
            E-Way Bill Management
          </h1>
          <p className="text-sm sm:text-base text-muted-foreground mt-1">
            Manage E-Way Bills for goods transportation
          </p>
        </div>
      </div>

      {/* Sync Component */}
      <EWayBillSync onSyncComplete={handleSyncComplete} />

      {/* Tabs for different views */}
      <Tabs defaultValue="portal" className="space-y-4">
        <TabsList>
          <TabsTrigger value="portal" className="gap-2">
            <Truck className="w-4 h-4" />
            Portal E-Way Bills
          </TabsTrigger>
          <TabsTrigger value="generated" className="gap-2">
            <FileText className="w-4 h-4" />
            Generated by Us
          </TabsTrigger>
        </TabsList>

        {/* Portal E-Way Bills Tab */}
        <TabsContent value="portal" className="space-y-4">
          <PortalEWayBillsViewer key={refreshKey} />
        </TabsContent>

        {/* Our Generated E-Way Bills Tab */}
        <TabsContent value="generated" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                E-Way Bills Generated by Us
              </CardTitle>
              <CardDescription>
                View and manage E-Way Bills generated for your invoices
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <FileText className="w-12 h-12 text-muted-foreground mb-4" />
                <h3 className="text-lg font-semibold">View Invoice-wise E-Way Bills</h3>
                <p className="text-muted-foreground mb-4">
                  E-Way Bills are managed at the invoice level. Visit individual invoice pages to view and manage their E-Way Bills.
                </p>
                <Link href="/invoices">
                  <Button>
                    Go to Invoices
                  </Button>
                </Link>
              </div>

              {/* Info Box */}
              <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg text-sm space-y-2">
                <p className="font-medium text-blue-900">How to generate E-Way Bills:</p>
                <ul className="list-disc pl-5 text-blue-800 space-y-1">
                  <li>Go to any invoice with amount ≥ ₹50,000</li>
                  <li>Click "Generate E-Way Bill" button</li>
                  <li>E-Way Bill will be auto-generated from invoice details</li>
                  <li>You can update vehicle, extend validity, or cancel from invoice page</li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Quick Stats Card */}
      <Card>
        <CardHeader>
          <CardTitle>E-Way Bill Quick Reference</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-3">
          <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
            <h4 className="font-medium text-green-900 mb-2">Required When</h4>
            <ul className="text-sm text-green-800 space-y-1">
              <li>✓ Goods value ≥ ₹50,000</li>
              <li>✓ Inter-state movement</li>
              <li>✓ Some intra-state (state-specific)</li>
            </ul>
          </div>

          <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <h4 className="font-medium text-blue-900 mb-2">Validity Period</h4>
            <ul className="text-sm text-blue-800 space-y-1">
              <li>• Road: 1 day per 100 KM</li>
              <li>• Rail/Air/Ship: As per transport</li>
              <li>• Can be extended with reason</li>
            </ul>
          </div>

          <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg">
            <h4 className="font-medium text-amber-900 mb-2">Important Notes</h4>
            <ul className="text-sm text-amber-800 space-y-1">
              <li>⚠ Cancel within 24 hours only</li>
              <li>⚠ Vehicle updatable anytime</li>
              <li>⚠ Required before dispatch</li>
            </ul>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
